name: Transpile and Build Check
on: [pull_request]

jobs:
  builds:
    if: "!contains(github.event.pull_request.title, 'WIP!')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://npm.pkg.github.com/'

      - name: Install Dependencies
        run: yarn --frozen-lockfile --ignore-platform

      - name: Run Build Command
        run: |
          yarn
          yarn build
